### ISSUE TITLE
Scaffold out the project

### ISSUE THREAD

**Issue by aulneau** [blockstack/keychain#1]
We need to use babel. Maybe consider using microbundle -> https://github.com/developit/microbundle

example lib using it: https://github.com/HenrikJoreteg/redux-bundler

**Comment by hstove** [comment]
Since we'll be building this package with TypeScript, we'll likely want to follow the coding standards of blockstack.js.

**Comment by aulneau** [comment]
Sure! that sounds good to me!

**Comment by hstove** [comment]
BTW - that means using Babel for general compilation, with TypeScript behind the scenes.

**Comment by markmhendrickson** [comment]
Is this issue still relevant given how far along we are with the project? Please close out if not.
