### ISSUE TITLE
Pull out code from blockstack browser

### ISSUE THREAD

**Issue by aulneau** [blockstack/keychain#2]

**Comment by hstove** [comment]
Spitballing some aspects of the code we want for this:

- Generating 12-word seeds
- Creating keychains derived from a seed, for apps, identities, and collections.
- Backwards compatible with the Browser for the above derivations
- Everything fully typed
- Deriving Gaia addresses from your keychain
- Encrypting content at different derivation paths (i.e. use your identity derivation to encrypt settings for a specific identity)

**Comment by markmhendrickson** [comment]
@hstove I presume we can close this out now? Or do you need to pull anything out into new issues first?
