### ISSUE TITLE
Build tests from Browser-related tests

### ISSUE THREAD

**Issue by hstove** [blockstack/keychain#3]
We'll want to set up tests (likely using Jest), and would want to re-use many tests from the existing Browser

**Comment by hstove** [comment]
- Support for code coverage reporting, including automated code coverage reporting in Github (same as blockstack.js)
- Out-of-the-box support for watching your code and running relevant tests (basically built into Jest already)

**Comment by markmhendrickson** [comment]
cc @timstackblock

**Comment by hstove** [comment]
Given the cc of Tim, I'd also want to add a point here that we want multiple types of tests:

- Some kind of faster, unit-based testing of business logic and individual components
- Some end-to-end testing integration testing of the apps, similar to the Selenium tests we have for the Browser and Explorer

**Comment by timstackblock** [comment]
Are these test for app.co or for the new Blockstack browser replacement please elaborate

**Comment by hstove** [comment]
These are unit tests only for the keychain package, which is a package that will use code from the browser. So that would not include the integration tests from the browser.

**Comment by timstackblock** [comment]
Ok gotcha @markmhx unit test for the package are developer test for their new code. But I can definitely help out with the task below. 

> Some end-to-end testing integration testing of the apps, similar to the Selenium tests we have for the Browser and Explorer. 

Do we have use cases of how this will be used End to end by the user, in the real world, I can create Serenity test for these?

**Comment by markmhendrickson** [comment]
I don't have any solid use cases in mind yet for integration tests. @hstove do you? Are unit and functional tests best tracked by one / this issue or would it be best to split into two plus issues to track all the various testing needs?

**Comment by markmhendrickson** [comment]
@hstove any updates here? Is this issue still relevant?
